import {
  User,
  Company,
  FiscalMetric,
  FiscalHealthIndicator,
  FiscalObligation,
  Alert,
  Document,
  CFDI,
  ChatMessage,
  FiscalScenario,
  CalendarEvent,
  Notification,
  DeductionOpportunity,
  BenchmarkData,
} from '@/types';

export const mockUser: User = {
  id: '1',
  name: 'María González',
  email: 'maria.gonzalez@empresaejemplo.com',
  role: 'user',
  phone: '+52 55 1234 5678',
  avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b47c?w=150&h=150&fit=crop&crop=face',
  createdAt: new Date('2024-01-15'),
  company: {
    id: '1',
    name: 'Distribuidora El Sol S.A. de C.V.',
    rfc: 'DES940527ABC',
    fiscalRegime: 'General de Ley Personas Morales',
    address: 'Av. Insurgentes Sur 123, Col. Roma Norte, CDMX',
    industry: 'Comercio al por menor',
    size: 'medium',
    createdAt: new Date('2019-03-15'),
  },
};

export const mockFiscalMetrics: FiscalMetric[] = [
  {
    id: '1',
    name: 'Ingresos Mensuales',
    value: 2850000,
    previousValue: 2650000,
    change: 7.5,
    changeType: 'increase',
    icon: 'TrendingUp',
    color: 'success',
    period: 'Noviembre 2024',
  },
  {
    id: '2',
    name: 'ISR por Pagar',
    value: 285000,
    previousValue: 312000,
    change: -8.7,
    changeType: 'decrease',
    icon: 'Receipt',
    color: 'primary',
    period: 'Noviembre 2024',
  },
  {
    id: '3',
    name: 'IVA Acreditable',
    value: 185000,
    previousValue: 175000,
    change: 5.7,
    changeType: 'increase',
    icon: 'Calculator',
    color: 'warning',
    period: 'Noviembre 2024',
  },
  {
    id: '4',
    name: 'Deducciones Aplicadas',
    value: 1250000,
    previousValue: 1180000,
    change: 5.9,
    changeType: 'increase',
    icon: 'PiggyBank',
    color: 'success',
    period: 'Noviembre 2024',
  },
];

export const mockFiscalHealth: FiscalHealthIndicator = {
  overall: 'high',
  score: 85,
  factors: {
    compliance: 92,
    documentation: 78,
    declarations: 88,
    deductions: 82,
  },
  recommendations: [
    'Mejorar organización documental para aumentar score de 78% a 85%',
    'Revisar deducciones pendientes por aplicar - potencial ahorro de $45,000',
    'Implementar alertas automáticas para fechas de declaración',
  ],
};

export const mockFiscalObligations: FiscalObligation[] = [
  {
    id: '1',
    title: 'Declaración Mensual ISR',
    description: 'Presentación de declaración mensual del Impuesto Sobre la Renta',
    dueDate: new Date('2024-12-17'),
    status: 'pending',
    priority: 'high',
    type: 'declaration',
    amount: 285000,
  },
  {
    id: '2',
    title: 'Pago IVA Noviembre',
    description: 'Pago del Impuesto al Valor Agregado correspondiente al mes de noviembre',
    dueDate: new Date('2024-12-17'),
    status: 'pending',
    priority: 'high',
    type: 'payment',
    amount: 125000,
  },
  {
    id: '3',
    title: 'Declaración Informativa DIOT',
    description: 'Declaración Informativa de Operaciones con Terceros',
    dueDate: new Date('2024-12-30'),
    status: 'pending',
    priority: 'medium',
    type: 'filing',
  },
  {
    id: '4',
    title: 'Entero de Retenciones',
    description: 'Entero de retenciones de ISR realizadas a trabajadores',
    dueDate: new Date('2024-12-17'),
    status: 'completed',
    priority: 'medium',
    type: 'payment',
    amount: 45000,
  },
];

export const mockAlerts: Alert[] = [
  {
    id: '1',
    title: 'Riesgo de Multa SAT',
    message: 'Se detectaron 3 facturas sin complemento de pago que podrían generar multas por $15,000',
    type: 'risk',
    severity: 'high',
    status: 'active',
    createdAt: new Date('2024-11-28'),
    actionRequired: true,
    relatedDocument: 'facturas-noviembre-2024',
  },
  {
    id: '2',
    title: 'Oportunidad de Ahorro',
    message: 'Se identificaron gastos de capacitación por $25,000 que pueden ser deducibles al 100%',
    type: 'opportunity',
    severity: 'medium',
    status: 'active',
    createdAt: new Date('2024-11-27'),
    actionRequired: false,
  },
  {
    id: '3',
    title: 'Fecha Límite Próxima',
    message: 'La declaración mensual de ISR vence en 3 días (17 de diciembre)',
    type: 'deadline',
    severity: 'high',
    status: 'active',
    createdAt: new Date('2024-12-14'),
    actionRequired: true,
  },
  {
    id: '4',
    title: 'Actualización Legislativa',
    message: 'Nueva resolución del SAT sobre deducciones de combustible. Revisar impacto en su empresa.',
    type: 'compliance',
    severity: 'medium',
    status: 'active',
    createdAt: new Date('2024-11-25'),
    actionRequired: false,
  },
];

export const mockDocuments: Document[] = [
  {
    id: '1',
    name: 'Factura_A123456_Nov2024.pdf',
    type: 'invoice',
    category: 'Gastos Generales',
    uploadDate: new Date('2024-11-28'),
    size: 245760,
    status: 'processed',
    url: '/documents/factura-a123456.pdf',
    tags: ['gastos', 'noviembre', 'procesada'],
    extractedData: {
      total: 15000,
      iva: 2400,
      rfc: 'XAXX010101000',
      fecha: '2024-11-25',
    },
  },
  {
    id: '2',
    name: 'Recibo_Servicios_Nov2024.pdf',
    type: 'receipt',
    category: 'Servicios',
    uploadDate: new Date('2024-11-27'),
    size: 156432,
    status: 'processed',
    url: '/documents/recibo-servicios.pdf',
    tags: ['servicios', 'luz', 'noviembre'],
  },
  {
    id: '3',
    name: 'Estado_Cuenta_Bancario_Nov2024.pdf',
    type: 'statement',
    category: 'Estados Financieros',
    uploadDate: new Date('2024-11-26'),
    size: 789123,
    status: 'processing',
    url: '/documents/estado-cuenta.pdf',
    tags: ['bancario', 'noviembre', 'procesando'],
  },
];

export const mockCFDIs: CFDI[] = [
  {
    id: '1',
    uuid: '12345678-1234-1234-1234-123456789ABC',
    rfc: 'DES940527ABC',
    issueDate: new Date('2024-11-25'),
    total: 58000,
    status: 'valid',
    type: 'issued',
    concept: 'Venta de productos alimenticios',
    taxAmount: 9280,
    category: 'Ingresos',
  },
  {
    id: '2',
    uuid: '87654321-4321-4321-4321-CBA987654321',
    rfc: 'PRO850315XYZ',
    issueDate: new Date('2024-11-24'),
    total: 25000,
    status: 'valid',
    type: 'received',
    concept: 'Compra de mercancía',
    taxAmount: 4000,
    category: 'Gastos',
  },
  {
    id: '3',
    uuid: '11111111-2222-3333-4444-555555555555',
    rfc: 'SER920412DEF',
    issueDate: new Date('2024-11-23'),
    total: 8500,
    status: 'valid',
    type: 'received',
    concept: 'Servicios de consultoría',
    taxAmount: 1360,
    category: 'Servicios',
  },
];

export const mockCalendarEvents: CalendarEvent[] = [
  {
    id: '1',
    title: 'Declaración Mensual ISR',
    date: new Date('2024-12-17'),
    type: 'deadline',
    description: 'Fecha límite para presentar declaración mensual',
    status: 'upcoming',
    priority: 'high',
  },
  {
    id: '2',
    title: 'Pago IVA',
    date: new Date('2024-12-17'),
    type: 'deadline',
    description: 'Pago del IVA correspondiente al mes',
    status: 'upcoming',
    priority: 'high',
  },
  {
    id: '3',
    title: 'Reunión con contador',
    date: new Date('2024-12-20'),
    type: 'meeting',
    description: 'Revisión de cierre anual',
    status: 'upcoming',
    priority: 'medium',
  },
  {
    id: '4',
    title: 'DIOT Diciembre',
    date: new Date('2024-12-30'),
    type: 'deadline',
    description: 'Presentación de DIOT',
    status: 'upcoming',
    priority: 'medium',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: '1',
    title: 'Declaración Completada',
    message: 'Su declaración mensual de octubre ha sido procesada exitosamente',
    type: 'success',
    read: false,
    createdAt: new Date('2024-11-28T10:30:00'),
  },
  {
    id: '2',
    title: 'Documentos Pendientes',
    message: 'Tiene 3 documentos pendientes de clasificar',
    type: 'warning',
    read: false,
    createdAt: new Date('2024-11-27T15:45:00'),
    actionUrl: '/documents',
  },
  {
    id: '3',
    title: 'Nueva Funcionalidad',
    message: 'Ya está disponible el simulador de escenarios fiscales',
    type: 'info',
    read: true,
    createdAt: new Date('2024-11-26T09:15:00'),
    actionUrl: '/optimization',
  },
];

export const mockDeductionOpportunities: DeductionOpportunity[] = [
  {
    id: '1',
    category: 'Capacitación',
    description: 'Gastos en cursos y certificaciones para empleados son 100% deducibles',
    estimatedSavings: 7500,
    difficulty: 'easy',
    requirements: ['Facturas con RFC', 'Comprobantes de pago', 'Constancias de capacitación'],
    deadline: new Date('2024-12-31'),
    status: 'available',
  },
  {
    id: '2',
    category: 'Tecnología',
    description: 'Equipos de cómputo y software pueden depreciarse aceleradamente',
    estimatedSavings: 12000,
    difficulty: 'medium',
    requirements: ['Facturas de equipo', 'Registro en activos fijos', 'Aplicación de depreciación'],
    status: 'available',
  },
  {
    id: '3',
    category: 'Combustible',
    description: 'Optimizar deducciones de combustible según nueva normativa SAT',
    estimatedSavings: 4500,
    difficulty: 'complex',
    requirements: ['Tarjetas de crédito o débito', 'Bitácora de viajes', 'CFDI con complemento'],
    status: 'in_progress',
  },
];

export const mockBenchmarkData: BenchmarkData = {
  industry: 'Comercio al por menor',
  metrics: {
    averageTaxRate: 22.5,
    averageDeductions: 35.2,
    complianceScore: 78.5,
    averageRefund: 15000,
  },
  comparison: {
    taxEfficiency: 'above',
    deductionUtilization: 'above',
    complianceLevel: 'above',
  },
};

export const mockChatMessages: ChatMessage[] = [
  {
    id: '1',
    message: 'Hola, ¿en qué puedo ayudarte hoy?',
    sender: 'assistant',
    timestamp: new Date('2024-11-28T09:00:00'),
    type: 'text',
  },
  {
    id: '2',
    message: '¿Cuáles son mis obligaciones fiscales pendientes?',
    sender: 'user',
    timestamp: new Date('2024-11-28T09:01:00'),
    type: 'text',
  },
  {
    id: '3',
    message: 'Tienes las siguientes obligaciones pendientes: 1) Declaración mensual ISR (vence 17 dic), 2) Pago IVA noviembre (vence 17 dic), 3) DIOT diciembre (vence 30 dic). ¿Te ayudo con alguna en particular?',
    sender: 'assistant',
    timestamp: new Date('2024-11-28T09:01:30'),
    type: 'text',
  },
];

export const mockFiscalScenarios: FiscalScenario[] = [
  {
    id: '1',
    name: 'Escenario Actual',
    description: 'Situación fiscal actual de la empresa',
    parameters: {
      income: 2850000,
      expenses: 2200000,
      deductions: 450000,
      taxRate: 30,
    },
    results: {
      estimatedTax: 195000,
      savings: 0,
      recommendations: [
        'Considerar aumentar deducciones autorizadas',
        'Evaluar cambio de régimen fiscal',
      ],
    },
    createdAt: new Date('2024-11-28'),
  },
  {
    id: '2',
    name: 'Optimización Propuesta',
    description: 'Escenario con optimizaciones fiscales aplicadas',
    parameters: {
      income: 2850000,
      expenses: 2200000,
      deductions: 550000,
      taxRate: 30,
    },
    results: {
      estimatedTax: 165000,
      savings: 30000,
      recommendations: [
        'Aplicar deducciones de capacitación identificadas',
        'Implementar depreciación acelerada de equipo',
      ],
    },
    createdAt: new Date('2024-11-28'),
  },
]; 